INSERT INTO persona VALUES (null,'Lorena Inmaculada', 'Barrios Araque', '8705216', '');
INSERT INTO persona VALUES (null,'Eduard Enrique', 'Bastidas Moreno', '14533006', '');
INSERT INTO persona VALUES (null,'César Agusto', 'Díaz Piñero', '16748327', '');
INSERT INTO persona VALUES (null,'German Ulises', 'Guaiga Guacaran', '15410007', '');
INSERT INTO persona VALUES (null,'Carlos José', 'Malave López ', '17216369', '');
INSERT INTO persona VALUES (null,'Jorge', 'Mechan', '13918410', '');
INSERT INTO persona VALUES (null,'Pedro Luís', 'Mujica Gúzman', '13162371', '');
INSERT INTO persona VALUES (null,'Luis', 'Ng Tso', '16563351', '');
INSERT INTO persona VALUES (null,'Hugo José', 'Rodriguez Gil', '3413786', '');
INSERT INTO persona VALUES (null,'Susana', 'Villamizar', '6544644', '');
INSERT INTO persona VALUES (null,'John Jesús', 'Yepez Malpica ', '18404375', '');
INSERT INTO persona VALUES (null,'Rafael', 'Barrera', '19504367', '');
